### ISSUE TITLE
Issue connecting to other containers via HostPath

### ISSUE THREAD

**Issue by SaintNick1214** [zee-ahmed/kube-rclone#12]
I'm quite confused how to successfully connect the mount to other pods in a managed Kuberentes cluster in OVH.  I've tried mounting the hostpath to other pods through a PV, but to no avail.

Could you add a quick tutorial in the project description explaining how to use the rclone daemonset in other pods?  It might be possible to sidecar the whole thing on other pods, but I think this is not in the spirit of the project.

**Comment by SaintNick1214** [comment]
I figured out what was happening. The project config is something like thisfor the hostpath mount:

```
        hostPath:
          path: /mnt/dir
```

However, when deployed, kubernetes automatically adds a line for Type: ""

```
      - name: media
        hostPath:
          path: /mnt/dir
          type: ""
```

This caused the host to never get the mount.  Change default config to include type like so:

```
      - name: media
        hostPath:
          path: /mnt/dir
          type: DirectoryOrCreate
```
