### ISSUE TITLE
rclone v1.53.1 not pushed to quay.io

### ISSUE THREAD

**Issue by nylonee** [zee-ahmed/kube-rclone#9]
The current helm charts fail because rclone v1.53.1 is not pushed to quay.io:
https://quay.io/repository/simplyzee/kube-rclone?tag=v1.53.1&tab=tags

This can be fixed by pushing the image, or changing the repository to Docker hub:
```
images:
  container:
    repository: rclone/rclone
    tag: 1.53.1
```
